### ISSUE TITLE
Sorry, I want to click image in zefyr editor and show full screen preview image in new page ?

### ISSUE THREAD

**Issue by mossnana** [memspace/zefyr#296]
Sorry, I want to click image in zefyr editor and show full screen preview image in new page ?
## Steps to Reproduce

1. I tried to insert GestureDetector() cover Image widget in buildImage function but it didn't work.

## Logs
-- No Error, but didn't work --

```dart
@override
  Widget buildImage(BuildContext context, String key) {
    final file = File.fromUri(Uri.parse(key));
    final image = FileImage(file);
    return GestureDetector (
      onTap() {
        print('xxx')
      },
      child: Image(image: image)
    )
}
```

**Comment by cgestes** [comment]
for the gesture detector to works you have a bit of work to do.. I am currently cleaning something that would allow it to work...

see the dirty:  https://github.com/cgestes/zefyr/commit/7c8cbd96649442b01b38be0298115219d7432728

Basically, we have a layer on top of all 'widgets' in zefyr for the selection. It needs to be disable for the area where we want to let gesture happens underneath. (image, blocks, ...).

One simple hack for you would be to use a listener instead of a gesture detector.

You can debug gesturedetector priority using: ```debugPrintGestureArenaDiagnostics = true;```

Hope it helps.

**Comment by mossnana** [comment]
> for the gesture detector to works you have a bit of work to do.. I am currently cleaning something that would allow it to work...
> 
> see the dirty: [cgestes@7c8cbd9](https://github.com/cgestes/zefyr/commit/7c8cbd96649442b01b38be0298115219d7432728)
> 
> Basically, we have a layer on top of all 'widgets' in zefyr for the selection. It needs to be disable for the area where we want to let gesture happens underneath. (image, blocks, ...).
> 
> One simple hack for you would be to use a listener instead of a gesture detector.
> 
> You can debug gesturedetector priority using: `debugPrintGestureArenaDiagnostics = true;`
> 
> Hope it helps.

Thank you for suggested. Very helpful
