### ISSUE TITLE
添加图片时华为安卓版本10手机上崩溃

### ISSUE THREAD

**Issue by ccmaia1218** [memspace/zefyr#425]
![微信图片_20201016113127](https://user-images.githubusercontent.com/70873738/96209837-259c0580-0fa3-11eb-8c99-b19bd78d921b.png)

```
```

```
```
![image](https://user-images.githubusercontent.com/70873738/96209882-43696a80-0fa3-11eb-8b10-c2e16340346a.png)

**Comment by ccmaia1218** [comment]
知道错误了

**Comment by SeasonLeee** [comment]
@ccmaia1218 嘿，如果你知道怎么解决的话，你可以自己关闭这个issue了

To those who wonder what happen and confuse by the foreign language, the issue author is asking how to resolve a clash problem happens when add image on Huawei phone where Android OS is 10.

And he also stated that he found out what the error was produced, so whoever is able to close this issue can proceed now.

**Comment by cgestes** [comment]
Closing. Thx for translating :)
