### ISSUE TITLE
Error: The non-abstract class 'InputConnectionController' is missing implementations 

### ISSUE THREAD

**Issue by sampy1998** [memspace/zefyr#508]
## Steps to Reproduce

I just upgraded my flutter and zefyr too and it is constantly showing this error 
can anyone please help me resolve this

```- TextInputClient.connectionClosed
 - TextInputClient.currentAutofillScope
 - TextInputClient.currentTextEditingValue
 - TextInputClient.performPrivateCommand
 - TextInputClient.showAutocorrectionPromptRect
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.
```

**Comment by glynskyi** [comment]
FYI Zefyr package is not maintained. Please take a look on Zefyrka package instead of this one.

Zefyrka is a fork of Zefyr package with the following improvements:

- support of Flutter 2.0
- opt-in the null safety
- text color
- checked list items
- background color
- paragraph alignment
- paragraph indentation

**Comment by pulyaevskiy** [comment]
Please see `1.0-rc.*` releases on Pub for latest updates of Zefyr package.

https://pub.dev/packages/zefyr/versions/1.0.0-rc.1
