### ISSUE TITLE
Remove dependency on image_picker and url_launcher

### ISSUE THREAD

**Issue by pulyaevskiy** [memspace/zefyr#82]
There's been several cases when users couldn't upgrade their dependencies because of zefyr.

It would make more sense to remove dependency on image_picker and url_launcher and provide an API to allow user code hook into this functionality.

As added bonus this would also allow users to choose whichever plugin they prefer instead of the default ones.

**Comment by gedw99** [comment]
Hmm. How would they do this though ?
It's almost like dependency injection pattern approach maybe your thinking ?

Today I was working on a go-flutter aspect of this app to add select image to add. On desktop that involves opening the native desktop file picker.
Same goes for the camera

**Comment by stemuk** [comment]
@pulyaevskiy Any progress on this side? I recently ran into a similar issue where I wanted to use the latest version of `image_picker` (0.6.7), however since zefyr still relies on `image_picker 0.5.0` the version solving failed. So one 'simple' solution would be to update all zefyr dependencies in regular intervals (which is of course very time consuming) or to follow through on the solution proposed in this issue which seems to be the much better approach.

**Comment by stemuk** [comment]
@pulyaevskiy It would be a great temporary solution to go ahead and bump `image_picker` to the latest version (0.6.1) since the currently supported version by zefyr (0.5.0) has several severe issues that were solved in future versions. Or is it possible to force the update as a dependency overwrite?

**Comment by pulyaevskiy** [comment]
Yep, this was done a while back.
