### ISSUE TITLE
Incorrect rendering of bullet points in unordered lists when Chinese font is used

### ISSUE THREAD

**Issue by msterzhang** [memspace/zefyr#83]
### 1.How can I fix the confusion caused by different language heights?
![image](https://ww1.sinaimg.cn/large/006Fzy5igy1g09h0l4n13j30c70msdhi.jpg)

### 2.How do I get the content of the text？

**Comment by pulyaevskiy** [comment]
Thanks for reporting!

1. This looks like a bug in the widget that renders bullet lists. This needs to be fixed in Zefyr.

2. If you need plain-text version of the document use `document.toPlainText()`, otherwise you can use `document.toDelta()` which returns `Delta` representation of the document. You can either serialize Deltas to JSON (`jsonEncode(yourDelta)`) or convert to any other format if you have specific requirements.

**Comment by msterzhang** [comment]
Thank you for your reply, this project is really great.
