### ISSUE TITLE
Supporting OT Types

### ISSUE THREAD

**Issue by rawkode** [memspace/zefyr#9]
I may be mistaken, but I believe Notus is essentially an ot-type definition with different semantics to ottypes/richtext; is this the case? If so, what would be involved in supporting other types?

I'm looking to hook Zefyr up to ShareDB, which uses ottypes/rich-text

**Comment by pulyaevskiy** [comment]
I haven't looked into ottypes that much, to be honest. In this regard the answer would be: no, Notus is not an ot-type definition and is not based or inspired by that project in any way.

However, if I read correctly, they use the same Delta format for rich-text. This means that theoretically everything should "just work" since I tried to port Delta to Dart as close as possible to original implementation.

It is easy to Notus document to Delta:

```dart
final doc = getMyDocument();
final delta = doc.toDelta();
// Delta is JSON serializable:
final json = jsonEncode(delta);
```

To get all individual changes in a document you need to listen on `NotusDocument.changes` stream. Note that you need to be aware of the source of each change, it can be either `ChangeSource.local` or `ChangeSource.remote`. This allows to prevent composing the same change twice depending on current site. I suspect that ShareDB might even abstract this details away.

Hope this helps.

**Comment by rawkode** [comment]
Thanks, @pulyaevskiy. That's very useful.
